# Generated by Django 4.0.5 on 2022-06-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_slip',
            new_name='votes_to_skip',
        ),
    ]
